// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2O5TnaP7aVArssRj37ns1t8hEMFFxeo',
    appId: '1:47219235653:web:fefa322011503d3116fc2c',
    messagingSenderId: '47219235653',
    projectId: 'homihostel-57391',
    authDomain: 'homihostel-57391.firebaseapp.com',
    storageBucket: 'homihostel-57391.firebasestorage.app',
    measurementId: 'G-FP0D55BYD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPw_A_MLvMDaQzhoseyaVRa4RQoN117A',
    appId: '1:47219235653:android:66afa7e9b031cf2916fc2c',
    messagingSenderId: '47219235653',
    projectId: 'homihostel-57391',
    storageBucket: 'homihostel-57391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnEyCBkpGRZhmBvNNuaHpP49S9usR5Emw',
    appId: '1:47219235653:ios:b432ada0d642887e16fc2c',
    messagingSenderId: '47219235653',
    projectId: 'homihostel-57391',
    storageBucket: 'homihostel-57391.firebasestorage.app',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnEyCBkpGRZhmBvNNuaHpP49S9usR5Emw',
    appId: '1:47219235653:ios:b432ada0d642887e16fc2c',
    messagingSenderId: '47219235653',
    projectId: 'homihostel-57391',
    storageBucket: 'homihostel-57391.firebasestorage.app',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm2O5TnaP7aVArssRj37ns1t8hEMFFxeo',
    appId: '1:47219235653:web:4f3e79d8f7ca08e716fc2c',
    messagingSenderId: '47219235653',
    projectId: 'homihostel-57391',
    authDomain: 'homihostel-57391.firebaseapp.com',
    storageBucket: 'homihostel-57391.firebasestorage.app',
    measurementId: 'G-DRDJ8ZVNLM',
  );
}
